name: FoxSnow
version: 2.3
author: Kesims
main: me.Kesims.FoxSnow.main
api-version: 1.17
softdepend:
  - PlaceholderAPI
  - WorldGuard
commands:
  foxsnow:
    description: Main command
    aliases: [snow, fsnow, fs]